### ISSUE TITLE
Add support for ESC5, ESC7, ESC9, ESC11, and ESC15

### ISSUE THREAD

**Issue by bradyjmcl** [badsectorlabs/ludus_adcs#1]
RE: "If you want to implement or start working in a new feature, please open a question / discussion issue for it. No pull-request will be accepted without previous chat about the changes, independently if it is a new feature, already planned feature or small quick win."

I have a working fork of the role built that adds support for ESC5, ESC7, and ESC15. I have tested that the deployment builds the users/templates/permissions as required, and have tested these three escalations successfully with certipy on a brand-new deployment of the role. All documentation has been updated to reflect the additions and corresponding variables as well.

Additionally, I've written a script (and corresponding revisions to Ansible tasks) that adds ACLs to weaponize ESC13, since the current ESC13 implementation just has the placeholder in the task. I can leave that part out if you'd prefer just ESC5, ESC7, and ESC15.

I can make a clean fork and do all the fun stuff with the commits that you want, just wanted to make sure here before I put in that work.

**Comment by kernel-sanders** [comment]
That sounds great! I would happily accept this merge after testing.

**Comment by bradyjmcl** [comment]
Submitted https://github.com/badsectorlabs/ludus_adcs/pull/2. I also added ESC9 and ESC11 (had a bit of time while waiting for approval 😁 )

**Comment by kernel-sanders** [comment]
Closed with merge of #2. Thank you for your work on this!
